### ISSUE TITLE
Support for cf v3-set-health-check

### ISSUE THREAD

**Issue by skyfalke** [HappyTobi/cf-puppeteer#1]
Hiya HappyTobi,

I'd love to extend cf-puppeteer to support `cf v3-set-health-check` (cf. https://cli.cloudfoundry.org/en-US/cf/v3-set-health-check.html).
In particular, that command provides more control over the invocation timeout of health checks that I deem important not only for projects that I am working on.
Would you mind letting me contribute to cf-puppeteer?

Thanks and kind regards,
Matthias

**Comment by HappyTobi** [comment]
Your pull request was merged, issue will be closed
