### ISSUE TITLE
push does not attach any services

### ISSUE THREAD

**Issue by amalagaura** [HappyTobi/cf-puppeteer#10]
I changed my github username. It was ankursethi-uscis.

We upgraded to PCF 2.3.18 and the push gets past the Applying Manifest where it died last time. 
`cf zero-downtime-push app-name -f manifest.yml --no-start --no-route`

But this time it pushes but there are no services attached so the start fails. 

I also tried `cf v3-apply-manifest` without your plugin and it didn't work. So probably on this PCF version it is still broken. I think we will have to try after we upgrade to 2.5 or 2.6.

Is there anything else I should try besides `v3-apply-manifest` to attach services?

**Comment by HappyTobi** [comment]
have you tried the legacy option?
I can bring the most features also to the "legacy push"

**Comment by HappyTobi** [comment]
@amalagaura 
I started to back port the options "--no-route" and "--route-only" to the "--legacy-push" (v2).

Can you try to push you app with the:
`cf zero-downtime-push app-name -f manifest.yml --no-start --legacy-push`

**Comment by amalagaura** [comment]
@HappyTobi Should I try with 1.1.2 rc2 ?

**Comment by HappyTobi** [comment]
No I will release the final version tomorrow.
There you can use the route and no route option in combination with (—legacy-push) hope that work for  you.

**Comment by HappyTobi** [comment]
@amalagaura so the new version was released. 
Please try it the the "--legacy-push" in combination with "--no-route" etc.

Kind regards

**Comment by amalagaura** [comment]
@HappyTobi Awesome this worked! 

I pushed with the legacy manifest and the `--no-start` and it did upload the web app.

It also uploaded the non-route app and was able to skip its routes.

When doing the second stage of a non-route app what command should we send? There is no `--start-only` but I used `--route-only` seems to be working. This is good for us because we can use the same commands for the first and second stages for all apps and the push can handle if it has a route or not. Thanks!

**Comment by babuz** [comment]
I have 2 routes in my application, but I am getting only one route after deployment. But the intermediate `venerable application has this 2 routes, I have 2 instance of the application running and I am using --legacy-push options and adding one --env environment variable..
