### ISSUE TITLE
add Possibility to add dynamic Routes

### ISSUE THREAD

**Issue by ukleeberger** [HappyTobi/cf-puppeteer#13]
Hi,

in my use case i need the ability to add routes dynamically. With the cf cli you have the option to use the --hostname Argument or in case of a manifest File to use the feature variable substitution (see https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#variable-substitution).

As far as i know with cf-puppeteer it is not possible to either use the --hostname argument nor use --var Arguments to substitute vars in a manifest file.

Would be great to add such functionality.

**Comment by HappyTobi** [comment]
I dropped that feature some versions ago, but I can bring them back in the next version

**Comment by ukleeberger** [comment]
That would be great!

**Comment by HappyTobi** [comment]
I will release the new version today

**Comment by ukleeberger** [comment]
Thx for your work.
Is it possible to support the --var Argument?

**Comment by HappyTobi** [comment]
Hi @ukleeberger 

nope but i need some time, im working on some other new stuff right now (deployment hooks).
So if you have some time to wait than it's no problem.

Kind regards
