### ISSUE TITLE
Routing is coming

### ISSUE THREAD

**Issue by babuz** [HappyTobi/cf-puppeteer#16]
I have 2 routes in my existing application, but I am getting only one route after deployment. But the intermediate `venerable application has these 2 routes, I have 2 instances of the application running and I am using --legacy-push options and adding one --env environment variable.. Manifest doesn't have routes

**Comment by HappyTobi** [comment]
Hi @babuz,

i think you are also using the ` --route-only` option or?
This option only work when you have the routes in the manifest.

Kind regards

**Comment by babuz** [comment]
No , I am not using that option.

**Comment by HappyTobi** [comment]
Where should the routes come from when there not part of the manifest? (Legacy-Push use cf push direct)

**Comment by babuz** [comment]
we have added by using different jenkins pipeline, I think, the pipeline was creating dynamic manifest to add that specific route. I don't think there is some cf command to copy the routes from one application to another. you can close this issues
