### ISSUE TITLE
--env was working in 1.1.1 and not working in 1.1.3 version

### ISSUE THREAD

**Issue by babuz** [HappyTobi/cf-puppeteer#17]
>cf zero-downtime-push api-consent-management-service-test -f manifest-dev.yml --legacy-push --env KEY_NAME=value --show-crash-log

Incorrect Usage: the required arguments `ENV_VAR_NAME` and `ENV_VAR_VALUE` were not provided.. I think some issue with parsing the environment variable got changed for the format got changed

**Comment by HappyTobi** [comment]
Hi @babuz,

thanks for opening the issue.
I'll checked that and find out that there is an error.
I will release a new version of puppeteer very soon, i also working on automated build and more integration tests.

Kind regards
Tobi

**Comment by HappyTobi** [comment]
Fixed in new Version 1.2.0.
Please reopen or create a new issue if there is still a problem

**Comment by babuz** [comment]
Hi HappyTobi/cf-puppeteer,

Thanks for the quick response and update,
Still, the cf community showing 1.1.3 version, so I couldn't install  1.2.0
version to verify.

Could you update the plugins.cloundfoundry.org with new version?

thanks
Ganeshbabu R.

**Comment by HappyTobi** [comment]
Hi @babuz,

you can install that manually.
The pr for the new version on cf plugins need some time always.

The installation was documented in the readme

1. Download the latest release from GitHub.
https://github.com/HappyTobi/cf-puppeteer/releases/tag/1.2.0

2. Install the Plugin
`cf install-plugin path/to/downloaded/binary`

Kind regards
