### ISSUE TITLE
Vars file have not been used

### ISSUE THREAD

**Issue by mvscosta** [HappyTobi/cf-puppeteer#22]
Hi,

I'm trying to push some application, with this command:
cf zero-downtime-push $PCF_APP_NAME -p $ROOT_PATH/$PCF_APP_NAME -f $ROOT_PATH/$PCF_APP_NAME/manifest.yml --vars-file $ROOT_PATH/$PCF_APP_NAME/vars.yml --legacy-push -t 120 -t $TIME_OUT_BGD --show-crash-log

But the variables aren't loaded.
I'm using version 1.2.0 of the plugin and my cf version is 6.49.0+d0dfa93bb.2020-01-07

Maybe I'm doing something wrong or we have some problem with this functionality?

cf output:
$ cf zero-downtime-push $PCF_APP_NAME -p $ROOT_PATH/$PCF_APP_NAME -f $ROOT_PATH/$PCF_APP_NAME/manifest.yml --vars-file $ROOT_PATH/$PCF_APP_NAME/vars.yml --legacy-push -t 120 -t $TIME_OUT_BGD --show-crash-log
 No application with name: pcf-application1-venerable found
 Renaming app pcf-application1 to pcf-application1-venerable in org CustomAppsOrg / space DIT1 as ProcessBuild...
 OK
 Use legacy push
 start pushing application with arguments [push pcf-application1 -f /services/pcf-application1/manifest.yml --no-start --no-route -p /services/pcf-application1]
 Expected to find variables: app_new_relic_name, app_route1, data_entities_connection_string
 error while uploading / deploying the application... roll everything back
 Deleting app pcf-application1 in org CustomAppsOrg / space DIT1 as ProcessBuild...
 OK
 App pcf-application1 does not exist.
 Renaming app pcf-application1-venerable to pcf-application1 in org CustomAppsOrg / space DIT1 as ProcessBuild...
 OK
 FAILED
 error: exit status 1

Bests
Marcus

**Comment by HappyTobi** [comment]
Hi Marcus,

I added a new integration test for the vars file. 
I will also check that again and fix the issue if there is one.

Kind regards
Tobi

**Comment by HappyTobi** [comment]
Hi @mvscosta,

think there is a bug when you push the app with the `--legacy-push` and the `--vars-file` option.
I will check that and bring a fix with the 1.2.1 release.

Kind regards
Tobi

**Comment by HappyTobi** [comment]
Hi @mvscosta,

Please check the latest Build the issue was fixed there.

https://github.com/HappyTobi/cf-puppeteer/actions/runs/67715681

I will bring a release soon. (Waiting for some other feedback)

Kind regards

**Comment by HappyTobi** [comment]
I will close the issue. 
Your topic was fixed in the latest release 1.2.1
For more info read the blog post: [Post](https://cf-puppeteer.happytobi.com/posts/release_1.2.1/)
