### ISSUE TITLE
Route generation is broken

### ISSUE THREAD

**Issue by therealshark** [HappyTobi/cf-puppeteer#27]
Using cf-puppeteer 1.2.1
with the following manifest.yml:
```
applications:
- name: fastify
  env:
    OPTIMIZE_MEMORY: "true"
  routes:
  - route: bcd-test.the.hostname/api
```
perfectly works with `cf push -f manifest.yml` but fails with `cf zero-downtime-push --legacy-push -f manifest.yml`:

```
map routes to new application fastify
map route [map-route fastify the.hostname --hostname bcd-test./api]Creating route bcd-test.%2Fthe.hostname for org myorg / space myspace as user@mail...
FAILED
Error resolving route:
Server error, status code: 400, error code: 210001, message: The route is invalid: host format
could not map route bcd-test./the.hostname to application%!(EXTRA string=fastify)
Deleting app fastify-venerable in org myorg / space myspace as user@mail...
OK
```

**Comment by HappyTobi** [comment]
Hi,

I will add that to the test and check that.

Kind regards

**Comment by HappyTobi** [comment]
Hi @therealshark,

I found the issue! 
I just started to fix the problem. I will add the link to the github action build after it's working.
For updating the Plugin site it will took a while.

Kind regards

**Comment by HappyTobi** [comment]
@therealshark,

so I fixed the issue can you try the latest build pls? 
Just for verification.
 
https://github.com/HappyTobi/cf-puppeteer/actions/runs/113935243

Kind regards

**Comment by therealshark** [comment]
@HappyTobi i will check it out, thanks :)

**Comment by therealshark** [comment]
@HappyTobi works perfectly, thanks 👍

**Comment by therealshark** [comment]
I guess lets leave this issue open until it is released? Just close it whenever it makes sense for you :)

**Comment by HappyTobi** [comment]
I will later tag that issue and release the new Version.
But it will take a while till the release was available on the cf-plugin site.

**Comment by HappyTobi** [comment]
Issue was tagged. 
Fix will be release with the tagged version
