### ISSUE TITLE
Manifest attribute "buildpack" is deprecated

### ISSUE THREAD

**Issue by seinol** [HappyTobi/cf-puppeteer#4]
At first, thank you very much for taking over the further development and lifecycle of autopilot. We use autopilot very much on our CI/CD system.
As you probably know, the buildpack attribute in the manifest is now deprecated. Have you planned to change to the new attribute buildpacks? We would very much prefer a change soon.
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#buildpack

**Comment by HappyTobi** [comment]
Hi @seinol thanks for the Feedback.
I already changed the Format for puppeteer but the cf cli api can‘t use the new format.
I will invest some more time next week to support the new format.

**Comment by seinol** [comment]
I'm not sure if I misunderstood anything, but I can use `cf push -f path/to/manifest` with manifests which are using the new buildpacks attribute.

**Comment by HappyTobi** [comment]
if you write it in the new format you get an error i think (i've tested that some time before)

**Comment by seinol** [comment]
I'm sure now, `cf push` is working with a manifest with the new buildpacks attribut. 
How long do you think it will take for cf puppeteer to support the new attribute? A big migration depends on it on our site.

**Comment by HappyTobi** [comment]
Hi @seinol i just startet to work on, hope that i can finish it till end of next week

**Comment by seinol** [comment]
That would be very nice. Thank you very much 👍

**Comment by HappyTobi** [comment]
Hi @seinol i try to release a pre release today. 
I will also announce something in the blog / cf-puppeteer site.

**Comment by HappyTobi** [comment]
first rc was released hope everything is working as expected

**Comment by seinol** [comment]
Thanks for the pre-release @HappyTobi 
What do you think, until when can you make a full release and then also publish it in the cf cli community plugins repository(https://plugins.cloudfoundry.org/)? Or is it possible to put the pre-release version in the repository?
Our CI/CD system automatically installs the latest version of cf-puppeteer out of the cf-community plugin repository. It would be a little pain if we have to change all plans only to access this pre-release directly.

**Comment by seinol** [comment]
And unfortunately it seems that it is not working properly:

```
$ cf zero-downtime-push -f deployment/manifest-dev.yml
Umbenennen von App appname in appname-venerable in Organisation myOrg_apps / Bereich space-dev als USER...
OK
Error while calling the apply manifest url /actions/apply_manifest - error: Post /actions/apply_manifest: unsupported protocol scheme ""
vendor routes mapped to application - route guid f582a087-c783-47ef-902b-3c7d72f203de
post error: Post : unsupported protocol scheme ""
panic: Post : unsupported protocol scheme ""

goroutine 1 [running]:
github.com/happytobi/cf-puppeteer/cfResources.(*ResourcesData).UploadApplication(0xc000185bc0, 0xc00011a7e0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tobi/Documents/develop/opensource/go/src/github.com/happytobi/cf-puppeteer/cfResources/cfResources.go:515 +0x1056
main.getActionsForApp.func4(0x0, 0x0)
        /Users/tobi/Documents/develop/opensource/go/src/github.com/happytobi/cf-puppeteer/puppeteer.go:185 +0xbf3
github.com/happytobi/cf-puppeteer/rewind.Actions.Execute(0xc000197b90, 0x7, 0x7, 0x8ec905, 0x67, 0x0, 0x0)
        /Users/tobi/Documents/develop/opensource/go/src/github.com/happytobi/cf-puppeteer/rewind/rewind.go:13 +0x87
main.CfPuppeteerPlugin.Run(0x97adc0, 0xc000114850, 0xc00009e020, 0x3, 0x6)
        /Users/tobi/Documents/develop/opensource/go/src/github.com/happytobi/cf-puppeteer/puppeteer.go:289 +0x314
github.com/happytobi/cf-puppeteer/vendor/code.cloudfoundry.org/cli/plugin.Start(0x96de60, 0xcb71c8)
        /Users/tobi/Documents/develop/opensource/go/src/github.com/happytobi/cf-puppeteer/vendor/code.cloudfoundry.org/cli/plugin/plugin_shim.go:34 +0x28a
main.main()
        /Users/tobi/Documents/develop/opensource/go/src/github.com/happytobi/cf-puppeteer/puppeteer.go:30 +0x44
```

Manifest file:
```
applications:
- name: appname
  buildpacks:
  - https://github.com/cloudfoundry/php-buildpack.git
  path: ../src
  disk_quota: 2G
  env:
    PHP_ENV: production
  instances: 1
  memory: 256M
  routes:
  - route: url.example.com
  services:
  - ma-db
  - app-db
  - credentials
  stack: cflinuxfs3
```

**Comment by HappyTobi** [comment]
I think im using newer apis than your backend supports. 
Can you Tell me what the command „cf api“ prints?

**Comment by seinol** [comment]
```
$ cf api
API-Endpunkt:   https://api.example.com
API-Version:    2.128.0
```

**Comment by HappyTobi** [comment]
Thx, i‘ve used the api‘s from 2.134 i will check it

**Comment by seinol** [comment]
Our systems were updated last night and are now also available on api v2.134.
I tested again and had exactly the same errors than before with the older api version. I also tried with a newer cf cli version(6.44.1+c3b20bfbe.2019-05-08), but it made no difference.

**Comment by skyfalke** [comment]
Just tested the latest release candidate [1.0.0.rc.1](https://github.com/HappyTobi/cf-puppeteer/releases/tag/1.0.0.rc.1) with multi-buildpack Java apps that use the `buildpacks` property in their manifest files. Works like a charm for the deployments that I used it for so far.

**Comment by HappyTobi** [comment]
Hi @seinol,

version 1.0.0 is release with the newest release the issue if the multi buildpack issue is fixed.
I will close the issue, please open a new on if you have new / other issues with the newest version.

Kind regards
