### ISSUE TITLE
Route path

### ISSUE THREAD

**Issue by jmfulgham** [HappyTobi/cf-puppeteer#6]
I would like to be able to add a route path when running the deployment. Is this currently possible, or a work in progress?

Thanks so much!

**Comment by jmfulgham** [comment]
Missed the docs explaining how routes work. Apologies :)

**Comment by HappyTobi** [comment]
Have you also seen the Page for CF-Puppeteer? If you miss something please ask or give me some feedback.

https://cf-puppeteer.happytobi.com

Kind regards
