### ISSUE TITLE
FAILED error: unexpected end of JSON input

### ISSUE THREAD

**Issue by r-chris** [HappyTobi/cf-puppeteer#8]
Hi, upon deployment I see this error:

```
Deleting app bla-bla-dev in org BLA / space BLA as bla@bla...
OK
start uploading manifest file
OK
add routes to application
OK
map vendor routes to new application
.
OK
FAILED
error: unexpected end of JSON input
```

In the traced log (`export CF_PUPPETEER_TRACE=true`) I see:

```
response from get call to path: /v3/service_bindings was: %!s(<nil>)
response from get call to path: /v3/service_bindings was: %!s(<nil>)
response from get call to path: /v3/service_bindings was: %!s(<nil>)
try to call path: https://bits.XXX:443/packages/XXX
response from get call to path: https://bits.XXX:443/packages/XXX was: %!s(int=405)
FAILED
error: unexpected end of JSON input
```

**Comment by r-chris** [comment]
Am I correct to assume that I might have more success using the `--legacy-push` option here?

Is this possibly caused by the cloud provider (not us in this case) not supporting all of the latest `v3` API ?

**Comment by HappyTobi** [comment]
Hi Chris,

You can check the version with:
„less ~/.cf/config.json“
or 
„#cf curl/„

When you can only use v2 then use the „legacy-push“ option 

Kind regards

**Comment by r-chris** [comment]
Thanks, using the `--legacy-push` fixed this for me.
